table Orders {
  OrderID INTEGER [PRIMARY KEY]
  CustomerID INT
  EmployeeID INT
  OrderDate DATE
  ShipperID INT
}

table customers {
  CustomerID INTEGER [pk, increment]
  CustomerName VARCHAR(64)
  ContactName VARCHAR(64)
  Address VARCHAR(128)
  City VARCHAR(64)
  PostalCode VARCHAR(16)
  Country VARCHAR(64)
}